### PR TITLE
Define as independent module within bower exports

### PR DESCRIPTION
**Pull request by optyler**
An independent module for this directive will be useful.

### CODE REVIEW

**Comment by brantwills** [comment]
Hey @optyler thank you so much for the pull request!

I'm still learing bower, do you happen to have any articles or advice on why this is useful?

**Comment by optyler** [comment]
Hi, this is not only for bower but for comprehension purposes in code. Actually, people who want to use the `paging` directive should inject the `myApp` module. 

Here after, my main application module declaration : 
```javascript
var app = angular.module('anrcliApp', [
  'ngAnimate',
  'ngCookies',
  'ngResource',
  'ngRoute',
  'ngSanitize',
  'ngTouch',
  'services',
  'constants',
  'controllers',
  'directives',
  'filters',
  'folders',
  'oeilactu',
  'admin',
  'ui.router',
  'ngProgress',
  'uiSwitch',
  'readableTime',
  'vr.directives.slider'
  'myApp', /* module for paging directive */
]);
```
As you can see, the last dependency, without comments, isn't clear enough ;-)

**Comment by brantwills** [comment]
Ahh thanks I did not consider the approach of injecting 'myApp'
Makes me wonder if there is a better way to represent the core paging directive
This change will impact app.js - I'll get this rolled in as soon as possible

**Comment by optyler** [comment]
I don't know if there is a naming convention for modules names, but I think it's quite similar as packages names in java ;)

**Comment by homburg** [comment]
Hi!

Nice paging directive. I've updated `app.js` to reference `brantwills.paging`

Generally when defining a bower.json definition, the `main` list of files should define a self-contained module.

We include bower dependencies via https://www.npmjs.com/package/main-bower-files and the paging.js file generated errors because of the dependency on a module named `myApp`

**Comment by homburg** [comment]
And thanks @optyler for creating the PR :-)

**Comment by brantwills** [comment]
Looks awesome thanks guys! Apologies for the delay

**Comment by optyler** [comment]
lol, this is nothing, thank's to you to made this directive ;)

**Pull request merged**
