### PR TITLE
convert tabs to spaces

### PR DESCRIPTION
**Pull request by e-andrew**

### CODE REVIEW

**Comment by brantwills** [comment]
Hey e-andrew, dude thank you so much for bringing this up!
This issue has been eating at me for awhile now!

I would like to do some research around spacing considerations before pulling this in.
Do you happen to know any good articles or best practices you could recommend?

**Comment by brantwills** [comment]
Still have this one on the ole todo list - sorry for the delay

**Comment by e-andrew** [comment]
Oh, sorry. A big part of files has spaces instead tabs (in your project), thats why I converted tabs to spaces in all remaining files. 
(Sorry for english)

**Comment by brantwills** [comment]
Thanks again e-andrew!

**Pull request merged**
